### ISSUE TITLE
 Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by Dnstje** [Perfare/AssetStudio#177]
Im having issues after version v0.9.0.29 reading out the Mesh (Body) in models.
Aswell blendshapes or morphs werent included in the FBX file, as previous versions can output the mesh and successfully export it to a fbx file.
As for the unity files, those are compiled at 5.6.3p1, cached UnityFS.

`************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadSingle()
   at AssetStudio.Mesh.BlendShapeData..ctor(EndianBinaryReader reader) in C:\projects\assetstudio\AssetStudio\Classes\Mesh.cs:line 259
   at AssetStudio.Mesh..ctor(AssetPreloadData MeshPD, Boolean readSwitch) in C:\projects\assetstudio\AssetStudio\Classes\Mesh.cs:line 520
   at AssetStudio.AssetStudioForm.PreviewAsset(AssetPreloadData asset) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 852
   at AssetStudio.AssetStudioForm.selectAsset(Object sender, ListViewItemSelectionChangedEventArgs e) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 695
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

I can provide a file if it is needed for debugging.

**Comment by Perfare** [comment]
Please upload the file

**Comment by Dnstje** [comment]
Found another one as well, which is `System.OutOfMemoryException: Array dimensions exceeded supported range.`

As for the files : https://www.dropbox.com/s/d6duyinat2n42rv/195253454%28array%29?dl=0
and https://www.dropbox.com/s/sq0l3k9zbw0rto0/198924124%28unableread%29?dl=0

**Comment by Perfare** [comment]
Fixed

**Comment by umustbeloggedintododat** [comment]
nope not fixed encountering this issue
