### ISSUE TITLE
Export fails on GooglePlay sprite

### ISSUE THREAD

**Issue by apavlinovic** [Perfare/AssetStudio#217]
Fails in export, fails in the UI, not sure why!

APK: https://www.apkmirror.com/apk/next-games/the-walking-dead-our-world/the-walking-dead-our-world-0-170-2-6-release/the-walking-dead-our-world-0-170-2-6-android-apk-download/download/

Files failing, both found in Global Game Managers:

* GooglePlay (sprite)
* Icon_Currency_Weapon_Token (sprite)

----

**Stack trace**

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Drawing2D.GraphicsPath.AddPolygon(PointF[] points)
   at AssetStudio.SpriteHelper.CutImage(AssetPreloadData asset, AssetPreloadData texture2DAsset, RectangleF textureRect, Sprite sprite) in C:\projects\assetstudio\AssetStudio\StudioClasses\SpriteHelper.cs:line 74
   at AssetStudio.SpriteHelper.GetImageFromSprite(AssetPreloadData asset) in C:\projects\assetstudio\AssetStudio\StudioClasses\SpriteHelper.cs:line 34
   at AssetStudio.AssetStudioForm.PreviewAsset(AssetPreloadData asset) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 989
   at AssetStudio.AssetStudioForm.selectAsset(Object sender, ListViewItemSelectionChangedEventArgs e) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 685
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by HeresHavi** [comment]
Hey apavlinovic,

I managed to extract everything without a problem. Here's the .rar file in case you need it:
175.71 MB: https://www82.zippyshare.com/v/VVhgLoXW/file.html

**Comment by Stellarspace** [comment]
@apavlinovic Please close the issue if it’s been resolved.
