### ISSUE TITLE
Latest version (Unity Studio 0.10.0.56) crash on export all assets

### ISSUE THREAD

**Issue by TheEmbracedOne** [Perfare/AssetStudio#235]
Tried exporting by loading all folders then selecting "export all assets", I get an immediate crash. Tried it with two different games, both gotten a new updated version in the past few months, however when I tried extracting earlier game files, that worked.

For example, Hollow Knight's current public beta 1.3.3.7 can be exported without any issues, but a later build gets me an immediate crash, using the same version of the program. The files are definitely not big size and there shouldnt be any naming issues, not sure what causes this and there arent any logs I could find (saw some suggestions but doesnt seem to be implemented yet), and the fact that both games I tried this with got a new update recently, I suspect there might be something with a Unity update?

Please advise.

**Comment by TheEmbracedOne** [comment]
Some more info, in the event viewer, I found the following log:

```
Faulting application name: AssetStudio.exe, version: 0.10.0.56, time stamp: 0x5b574657
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff963870a4d
Faulting process ID: 0x303dc
Faulting application start time: 0x01d42432b203b7d1
Faulting application path: P:\Program Files\Unity Studio 0.10.0.56 64\AssetStudio.exe
Faulting module path: unknown
Report ID: aca9a2d5-9027-11e8-8252-d8cb8ac9ef6c
Faulting package full name: 
Faulting package-relative application ID: 
```

additionally, the program seems to hang at first for 10 secs or so while displaying "Exporting Animator: FlashEffect", then crashes, saying "AssetStudio has stoped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."

Win8.1 64bit is my OS

**Comment by TheEmbracedOne** [comment]
If I select an item that would otherwise crash the program during export, it gives me the following error. Hope this is more helpful than the above:

```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AssetStudio.Texture2DConverter..ctor(Texture2D m_Texture2D) in C:\projects\assetstudio\AssetStudio\StudioClasses\Texture2DConverter.cs:line 23
   at AssetStudio.AssetStudioForm.PreviewAsset(AssetPreloadData asset) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 709
   at AssetStudio.AssetStudioForm.selectAsset(Object sender, ListViewItemSelectionChangedEventArgs e) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 685
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AssetStudio
    Assembly Version: 0.10.0.56
    Win32 Version: 0.10.0.56
    CodeBase: file:///P:/Program%20Files/Unity%20Studio%200.10.0.56%2064/AssetStudio.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0
    CodeBase: file:///P:/Program%20Files/Unity%20Studio%200.10.0.56%2064/OpenTK.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0
    CodeBase: file:///P:/Program%20Files/Unity%20Studio%200.10.0.56%2064/OpenTK.GLControl.DLL
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Half
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///P:/Program%20Files/Unity%20Studio%200.10.0.56%2064/System.Half.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by TheEmbracedOne** [comment]
Thank you, I've tried that but unfortunately I still get some crashes even with that - some are Texture2D files, and there are some files that have a really messed up preview (and they export the same way), example of messed up preview here: https://i.imgur.com/Pg8csav.png
example of exported image that is messed up here: https://i.imgur.com/zmh97S9.png

Let me know if I can provide any further files or details to help you.

**Comment by Perfare** [comment]
It is the sprite texture, it is like this, not messed up.

**Comment by TheEmbracedOne** [comment]
![spriteatlastexture-bestiary_full-2048x2048-fmt12 050200194](https://user-images.githubusercontent.com/16197906/43233475-00f30f50-906e-11e8-8910-53f7724c983d.png)
Like this?

**Comment by HeresHavi** [comment]
Upload the file for Perfare to download so he can look into it.
