### ISSUE TITLE
Unhandled exception when opening AssetBundle

### ISSUE THREAD

**Issue by BowDown097** [Perfare/AssetStudio#542]
The game I'm attempting to mod has 3 main AssetBundles; btd6_megabundle, resource_bundle, and sprite_atlases. btd6_megabundle and sprite_atlases open perfectly fine, but when attempting to get resource_bundle, it fails to load with an unhandled exception. This exception is "An entry with the same key already exists." I get this after updating to the most recent AssetStudio.
```
System.ArgumentException: An entry with the same key already exists.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at AssetStudioGUI.Studio.BuildClassStructure() in C:\projects\assetstudio\AssetStudioGUI\Studio.cs:line 324
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AssetStudioGUI.AssetStudioGUIForm.<BuildAssetStructures>d__51.MoveNext() in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by Perfare** [comment]
already fixed.
